In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg  al  su     rbc        pc         pcc  \
0     2.000000  76.459948  c   3   0  normal  abnormal  notpresent   
1     3.000000  76.459948  c   2   0  normal    normal  notpresent   
2     4.000000  76.459948  a   1   0  normal    normal  notpresent   
3     5.000000  76.459948  d   1   0  normal    normal  notpresent   
4     5.000000  50.000000  c   0   0  normal    normal  notpresent   
..         ...        ... ..  ..  ..     ...       ...         ...   
394  51.492308  70.000000  a   0   0  normal    normal  notpresent   
395  51.492308  70.000000  c   0   2  normal    normal  notpresent   
396  51.492308  70.000000  c   3   0  normal    normal  notpresent   
397  51.492308  90.000000  a   0   0  normal    normal  notpresent   
398  51.492308  80.000000  a   0   0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)

In [5]:
dataset

age  bp  al  su  bgr   bu  sc  sod  pot  hrmo  ...  pc_normal  \
0      2  76   3   0  148   57   3  137    4    12  ...          0   
1      3  76   2   0  148   22   0  137    4    10  ...          1   
2      4  76   1   0   99   23   0  138    4    12  ...          1   
3      5  76   1   0  148   16   0  138    3     8  ...          1   
4      5  50   0   0  148   25   0  137    4    11  ...          1   
..   ...  ..  ..  ..  ...  ...  ..  ...  ...   ...  ...        ...   
394   51  70   0   0  219   36   1  139    3    12  ...          1   
395   51  70   0   2  220   68   2  137    4     8  ...          1   
396   51  70   3   0  110  115   6  134    2     9  ...          1   
397   51  90   0   0  207   80   6  142    5     8  ...          1   
398   51  80   0   0  100   49   1  140    5    16  ...          1   

     pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  \
0              0           0        0       0        0          1       1   
1              0           0        0       0        0          1       0   
2              0           0        0       0        0          1       0   
3              0           0        0       0        0          1       0   
4              0           0        0       0        0          1       0   
..           ...         ...      ...     ...      ...        ...     ...   
394            0           0        0       0        0          1       0   
395            0           0        1       1        0          1       0   
396            0           0        1       1        0          0       0   
397            0           0        1       1        0          1       0   
398            0           0        0       0        0          1       0   

     ane_yes  classification_yes  
0          0                   1  
1          0                   1  
2          0                   1  
3          1                   1  
4          0                   1  
..       ...                 ...  
394        0                   1  
395        1                   1  
396        0                   1  
397        1                   1  
398        0                   0  

[399 rows x 28 columns]

In [6]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]

In [9]:
independent.shape

(399, 27)

In [10]:
independent

age  bp  al  su  bgr   bu  sc  sod  pot  hrmo  ...  rbc_normal  \
0      2  76   3   0  148   57   3  137    4    12  ...           1   
1      3  76   2   0  148   22   0  137    4    10  ...           1   
2      4  76   1   0   99   23   0  138    4    12  ...           1   
3      5  76   1   0  148   16   0  138    3     8  ...           1   
4      5  50   0   0  148   25   0  137    4    11  ...           1   
..   ...  ..  ..  ..  ...  ...  ..  ...  ...   ...  ...         ...   
394   51  70   0   0  219   36   1  139    3    12  ...           1   
395   51  70   0   2  220   68   2  137    4     8  ...           1   
396   51  70   3   0  110  115   6  134    2     9  ...           1   
397   51  90   0   0  207   80   6  142    5     8  ...           1   
398   51  80   0   0  100   49   1  140    5    16  ...           1   

     pc_normal  pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  \
0            0            0           0        0       0        0          1   
1            1            0           0        0       0        0          1   
2            1            0           0        0       0        0          1   
3            1            0           0        0       0        0          1   
4            1            0           0        0       0        0          1   
..         ...          ...         ...      ...     ...      ...        ...   
394          1            0           0        0       0        0          1   
395          1            0           0        1       1        0          1   
396          1            0           0        1       1        0          0   
397          1            0           0        1       1        0          1   
398          1            0           0        0       0        0          1   

     pe_yes  ane_yes  
0         1        0  
1         0        0  
2         0        0  
3         0        1  
4         0        0  
..      ...      ...  
394       0        0  
395       0        1  
396       0        0  
397       0        1  
398       0        0  

[399 rows x 27 columns]

In [11]:
dependent=dataset[['classification_yes']]

In [12]:
dependent

classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
x_train

array([[ 0.48747826,  1.80037959, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [ 0.30372406,  0.26198906, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.61504697, -0.5072062 , -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       ...,
       [-0.43129276,  0.26198906, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-1.35006379,  0.26198906, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456],
       [-0.06378435, -1.27640146, -0.68384276, ...,  0.51639778,
        -0.52223297, -0.44519456]])

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

C:\Users\saran\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [18]:
y_pred=classifier.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [23]:
from sklearn.metrics import classification_report
clf=classification_report(y_test,y_pred)

In [24]:
print("Report:\n",clf)

Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133



In [25]:
print("confusion matrix:\n",cm) 

confusion matrix:
 [[51  0]
 [ 3 79]]


In [28]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,y_pred,average='weighted')
print("The f1 macro value for best parameter {}:".format(classifier),f1_macro)

The f1 macro value for best parameter GaussianNB(): 0.9775556904684072


In [33]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,classifier.predict_proba(x_test)[:,1])

1.0

In [34]:
age_input=float(input("age:"))
bp_input=float(input("bp:"))
al_input=int(input("al:"))
su_input=int(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=int(input("pcv:"))
wc_input=float(input("wc:"))
rc_input=float(input("rc:"))
sg_b_input=int(input("sg_b:"))
sg_e_input=int(input("sg_e:"))
sg_d_input=int(input("sg_d:"))
sg_c_input=int(input("sg_c:"))
rbc_normal_input=int(input("rbc_normal:"))
pc_normal_input=int(input("pc_normal:"))
pcc_present_input=int(input("pcc_present:"))
ba_present_input=int(input("ba_present:"))
htn_yes_input=int(input("htn_yes:"))
dm_yes_input=int(input("dm_yes:"))
cad_yes_input=int(input("cad_yes:"))
appet_yes__input=int(input("appet_yes:"))
pe_yes_input=int(input("pe_yes:"))
ane_yes_input=int(input("ane_yes:"))


age:3.00
bp:70
al:3
su:0
bgr:130
bu:456
sc:134.8
sod:34
pot:23
hrmo:56
pcv:87
wc:8000
rc:578
sg_b:0
sg_e:1
sg_d:1
sg_c:1
rbc_normal:1
pc_normal:1
pcc_present:0
ba_present:0
htn_yes:0
dm_yes:0
cad_yes:0
appet_yes:0
pe_yes:0
ane_yes:0


In [44]:
result=classifier.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_e_input,sg_c_input,sg_d_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes__input,pe_yes_input,ane_yes_input]])

In [45]:
result

array([1])